Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SushiBarApp.Abstractions;
using SushiBarApp.Data.Models;
using Microsoft.AspNetCore.Http;

namespace SushiBarApp.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly Abstractions.IAuthorizationService _authorizationService;
        public AdminController(IProductService productService, ICategoryService categoryService, Abstractions.IAuthorizationService authorizationService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _authorizationService = authorizationService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.Categories = _productService.GetAllCategories();
            if (! await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            return View(await _productService.GetProducts(string.Empty));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid productId)
        {
            ViewBag.Categories = _productService.GetAllCategories();
            if (!await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            return View(await _productService.GetProductById(productId));
        }
        [HttpGet]
        public async Task<IActionResult> EditCategory(Guid categoryId)
        {
            if (!await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            return View( await _categoryService.GetCategory(categoryId));
        }
        [HttpGet]
        public async Task<IActionResult> CreateCategory()
        {
            if (!await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            return View(new Category());
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Product product, IFormFile image = null)
        {
            ViewBag.Categories = _productService.GetAllCategories();
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.Length];
                    image.OpenReadStream().Read(product.ImageData, 0, (int)image.Length);
                }
                await _productService.UpdateProduct(product);
                TempData["message"] = string.Format("Изменения в игре \"{0}\" были сохранены", product.Name);
                return RedirectToAction("Index");
            }
            TempData["error"] = "Ошибка изменения товара, некорректный ввод";
            return View(product);
        }
        [HttpGet]
        public async  Task<IActionResult> Create()
        {
            if (!await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            ViewBag.Categories = _productService.GetAllCategories();
            return View(new Product());
        }
    }
}

Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SushiBarApp.Abstractions;
using SushiBarApp.Data;
using SushiBarApp.Data.Models;

namespace SushiBarApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        [Authorize]
        public async Task<IActionResult> CreateCategory(Category category)
        {
            if (string.IsNullOrEmpty(category.Name))
                return RedirectToAction("CreateCategory", "Admin");
            await _categoryService.CreateCategory(category);
            TempData["message"] = string.Format("Категория \"{0}\" была успешно создана", category.Name);
            return RedirectToAction("Index", "Admin");
        }
        [Authorize]
        public async Task<IActionResult> ChangeCategoryName(Category category)
        {
            if (string.IsNullOrEmpty(category.Name))
                return RedirectToAction("EditCategory", "Admin", new {categoryId= category.Id});
            await _categoryService.ChangeCategoryName(category);
            TempData["message"] = string.Format("Категория \"{0}\" была успешно изменена", category.Name);
            return RedirectToAction("Index","Admin");
        }
        public async Task<string> GetCategoryNameById(Guid categoryId)
        {
            return await _categoryService.GetCategoryNameById(categoryId);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteCategory(Guid categoryId)
        {
            await _categoryService.DeleteCategory(categoryId);
            TempData["message"] = "Категория была успешно удалена";
            return RedirectToAction("Index", "Admin");
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SushiBarApp.Abstractions;
using SushiBarApp.Data;
using SushiBarApp.Data.Models;
using IAuthorizationService = SushiBarApp.Abstractions.IAuthorizationService;

namespace SushiBarApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IAuthorizationService _authorizationService;
        private readonly ShopCart _shopCart;

        public OrderController(IOrderService orderService,ShopCart shopCart, IAuthorizationService authorizationService)
        {
            _orderService = orderService;
            _shopCart = shopCart;
            _authorizationService = authorizationService;
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            var user = _authorizationService.GetUser(User.Claims);
            if (user == null)
                return View();
            return Checkout(new Order
            {
                Id = Guid.NewGuid(),
                Email = user.Email,
                Name = user.Name,
                OrderTime = DateTime.Now,
                Phone = user.PhoneNumber
            });
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            _shopCart.ListShopItems = _shopCart.GetShopItems();
            if (_shopCart.ListShopItems.Count == 0)
                ModelState.AddModelError("","Ваша корзина пуста");
            if (ModelState.IsValid)
            {
                _orderService.CreateOrder(order);
                return RedirectToAction("Complete");
            }
            return RedirectToAction("Index","ShopCart");
        }
        [HttpGet]
        public IActionResult Complete()
        {
            _shopCart.ClearShopCart();
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
        [HttpGet]
        public IActionResult GetAllOrders()
        {
            var user = _authorizationService.GetUser(User.Claims);
            if (user == null)
                return RedirectToAction("GetProducts", "Product");
            var list = _orderService.GetOrdersByEmail(user.Email);
            return View(list);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetOrdersByAdmin()
        {
            if (! await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("GetProducts", "Product");
            var orders = _orderService.GetOrders();
            return View(orders);
        }
        [HttpGet]
        public IActionResult GetOrderDetails(Guid orderId)
        {
            var details = _orderService.GetOrderDetails(orderId);
            return View(details);
        }
    }
}

Views/Admin/Create.cshtml
@model SushiBarApp.Data.Models.Product
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["error"] != null)
{
    <div class="alert alert-danger mt-4">@TempData["error"]</div>
}
<div class="panel">
    <div class="panel-heading">
        <h3>Создание товара</h3>
    </div>

    @using (Html.BeginForm("CreateProduct", "Product",
        FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.Id)
            
            <div class="form-group">
                    <label asp-for="@Model.Name"></label>
                    <div class="col-md-5">
                        <input asp-for="@Model.Name" class="form-control" />
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Description"></label>
                    <div class="col-md-5">
                        <textarea asp-for="@Model.Description" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="@Model.Description" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="form-group">
                    <label asp-for="@Model.Price"></label>
                    <div class="col-md-5">
                        <input asp-for="@Model.Price" placeholder="@Model.Price" type="number" class="form-control" />
                        <span asp-validation-for="@Model.Price" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Count"></label>
                    <div class="col-md-5">
                        <input asp-for="@Model.Count" type="number" class="form-control" />
                        <span asp-validation-for="@Model.Count" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Volume"></label>
                    <div class="col-md-5">
                        <input asp-for="@Model.Volume" type="number" class="form-control" />
                        <span asp-validation-for="@Model.Volume" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.CategoryId"></label>
                    <div class="col-md-5">
                        @foreach (Category cat in @ViewBag.Categories)
                        {
                            <input type="radio" name="CategoryId" value=@cat.Id asp-for="CategoryId" />
                            <label asp-for="CategoryId">@cat.Name</label><br/>
                        }
                        <span asp-validation-for=@Model.CategoryId class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for=@Model.IsFavourite></label>
                    <div class="col-md-5">
                        <input type="checkbox" class="custom-checkbox" name="IsFavourite" asp-for="@Model.IsFavourite" />
                        <span asp-validation-for="@Model.IsFavourite" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Type"></label>
                    <div class="col-md-5">
                        <label asp-for="@Model.Type">Еда</label>
                        <input type="radio" class="custom-radio" name="Type" value="Food" asp-for="@Model.Type" /><br />
                        <label asp-for=@Model.Type>Напиток</label>
                        <input type="radio" class="custom-radio" name="Type" value="Drink" asp-for="@Model.Type" />
                        <span asp-validation-for="@Model.Type" class="text-danger"></span>
                    </div>
                </div>

        </div>
        <div class="form-group">
            <div style="position: relative;">
                <label>Картинка</label>
                <a class='btn btn-link' href='javascript:;'>
                    Выберите файл...
                    <input type="file" name="Image" size="40"
                           style="position: absolute; z-index: 2; top: 0; left: 0; filter: alpha(opacity=0); opacity: 0; background-color: transparent; color: transparent;"
                           onchange='$("#upload-file-info").html($(this).val());'>
                </a>
                <span class='label label-info' id="upload-file-info"></span>
            </div>
            @if (Model.ImageData != null)
            {
                <img class="img-thumbnail" width="150" height="150"
                    src="@Url.Action("GetImage", "Product", new {productId = Model.Id})" />
            }
           
            <div class="panel-footer">
                <input type="submit" value="Сохранить" class="btn btn-primary"/>
                @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
                {
                    @class = "btn btn-default"
                })
            </div>
        </div>
    }
</div>

Views/Admin/CreateCategory.cshtml
@model Category
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-heading"><h3>Создание категории</h3></div>

@using (Html.BeginForm("CreateCategory", "Category",
   FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="text" class="form-control" placeholder="Введите название категории" asp-for="Name" />
    <input type="submit" value="Создать" class="btn btn-primary mt-2" />
    <a class="btn btn-outline-primary mt-2 ml-1" asp-action="Index" asp-controller="Admin">Назад</a>
}

Views/Admin/Edit.cshtml
@model SushiBarApp.Data.Models.Product
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="panel">
        <div class="panel-heading">
            @if (TempData["error"] != null)
            {
                <div class="alert alert-danger">@TempData["error"]</div>
            }
            <h3>Редактирование товара «@Model.Name»</h3>
        </div>

        @using (Html.BeginForm("Edit", "Admin",
           FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="panel-body">
                @Html.HiddenFor(m => m.Id)
                @Html.HiddenFor(m=>m.ImageData)
                @Html.HiddenFor(m=>m.ImageMimeType)
                <div class="form-group">
                    <label asp-for="@Model.Name"></label>
                    <div class="col-md-5">
                        <input asp-for="@Model.Name" class="form-control" />
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Description"></label>
                    <div class="col-md-5">
                        <textarea asp-for="@Model.Description" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="@Model.Description" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="form-group">
                    <label asp-for="@Model.Price"></label>
                    <div class="col-md-5">
                        <input asp-for="@Model.Price" type="number" class="form-control" />
                        <span asp-validation-for="@Model.Price" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Count"></label>
                    <div class="col-md-5">
                        <input asp-for="@Model.Count" type="number" class="form-control" />
                        <span asp-validation-for="@Model.Count" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Volume"></label>
                    <div class="col-md-5">
                        <input asp-for="@Model.Volume" type="number" class="form-control" />
                        <span asp-validation-for="@Model.Volume" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.CategoryId"></label>
                    <div class="col-md-5">
                        @foreach (Category cat in ViewBag.Categories)
                        {
                            <input type="radio" name="CategoryId" value=@cat.Id asp-for="CategoryId" />
                            <label asp-for="CategoryId">@cat.Name</label><br/>
                        }
                        <span asp-validation-for=@Model.CategoryId class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for=@Model.IsFavourite></label>
                    <div class="col-md-5">
                        <input type="checkbox" class="custom-checkbox" name="IsFavourite" asp-for="@Model.IsFavourite" />
                        <span asp-validation-for="@Model.IsFavourite" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Type"></label>
                    <div class="col-md-5">
                        <label asp-for="@Model.Type">Еда</label>
                        <input type="radio" class="custom-radio" name="Type" value="Food" asp-for="@Model.Type" /><br />
                        <label asp-for=@Model.Type>Напиток</label>
                        <input type="radio" class="custom-radio" name="Type" value="Drink" asp-for="@Model.Type" />
                        <span asp-validation-for="@Model.Type" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div style="position: relative;">
                        <label>Картинка</label>
                        <a class='btn btn-link' href='javascript:;'>
                            Выберите файл...
                            <input type="file" name="Image" size="40"
                                   style="position: absolute; z-index: 2; top: 0; left: 0; filter: alpha(opacity=0); opacity: 0; background-color: transparent; color: transparent;"
                                   onchange='$("#upload-file-info").html($(this).val());'>
                        </a>
                        <span class='label label-info' id="upload-file-info"></span>
                    </div>
                    @if (Model.ImageData != null)
                    {
                        <img class="img-thumbnail" width="150" height="150"
                             src="@Url.Action("GetImage", "Product", new {productId = Model.Id})" />
                    }
                </div>
            </div>
            <div class="panel-footer">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
                @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
                {
                    @class = "btn btn-default"
                })
            </div>
        }
    </div>

Views/Admin/EditCategory.cshtml
@model Category
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel-heading"><h3>Изменение категории "@Model.Name"</h3></div>

@using (Html.BeginForm("ChangeCategoryName", "Category",
  FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.Id)
    @Html.TextBox("Name", Model.Name, new { @class = "form-control" });
    <input type="submit" value="Изменить" class="btn btn-primary mt-2" />
    <a class="btn btn-outline-primary mt-2 ml-1" asp-action="Index" asp-controller="Admin">Назад</a>
}

Views/Admin/Index.cshtml
@model IEnumerable<Product>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["message"] != null)
{
    <div class="alert alert-success">@TempData["message"]</div>
}
<div class="panel panel-default">
    <div class="panel-heading"><h3>Список Категорий</h3></div>
    <table class="table table-striped table-condensed table-bordered w-50">
        <tr>
            <th class="text-center">Название</th>
            <th class="text-center">Айди категории</th>
            <th class="text-center">Действия</th>
        </tr>
        @foreach (Category item in ViewBag.Categories)
        {
            <tr>
                <td class="text-center">@Html.ActionLink(@item.Name, "EditCategory", "Admin", new { categoryId = item.Id })</td>
                <td class="text-center">@item.Id</td>
                <td class="text-center">
                    @using (Html.BeginForm("DeleteCategory", "Category", FormMethod.Post))
                    {
                        @Html.Hidden("categoryId", item.Id)
                        <input type="submit" class="btn btn-link" value="Удалить" />
                    }
                </td>
            </tr>
        }
    </table>
    <div class="panel-body">
        @Html.ActionLink("Посмотреть все заказы", "GetOrdersByAdmin", "Order", new { @class = "btn btn-primary" })<br />
        @Html.ActionLink("Добавить продукт", "Create", null, new { @class = "btn btn-primary" })<br />
        @Html.ActionLink("Добавить категорию", "CreateCategory", null, new { @class = "btn btn-primary" })
    </div>
    <div class="panel-heading">
        <h3>Список продуктов</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-center">Название</th>
                <th class="text-center">Категория</th>
                <th class="text-center">Цена</th>
                <th class="text-center">Штук</th>
                <th class="text-center">Грамм</th>
                <th class="text-center">Действия</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">@Html.ActionLink(@item.Name, "Edit", "Admin", new { productId = item.Id })</td>
                    <td class="text-center">@item.CategoryId</td>
                    <td class="text-center">@item.Price.ToString()</td>
                    <td class="text-center">@item.Count</td>
                    <td class="text-center">@item.Volume</td>
                    <td class="text-center">
                        @using (Html.BeginForm("DeleteProduct", "Product", FormMethod.Post))
                        {
                            @Html.Hidden("productId", item.Id)
                            <input type="submit" class="btn btn-link" value="Удалить" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>