Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using IronPython.Hosting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SushiBarApp.Abstractions;
using SushiBarApp.Data;
using SushiBarApp.Data.Models;

namespace SushiBarApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        SushiAppDBContext _context;

        public ProductController(IProductService productService,
            SushiAppDBContext context)
        {
            _productService = productService;
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> GetProducts(string categoryName)
        {
            ViewBag.CurrentCategory = categoryName;
            return View(await _productService.GetProducts(categoryName));
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateProduct(Product product, IFormFile image = null)
        {
            if (product.Id == Guid.Empty)
                product.Id = Guid.NewGuid();
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.Length];
                    image.OpenReadStream().Read(product.ImageData, 0, (int)image.Length);
                }
                await _productService.CreateProduct(product);
                TempData["message"] = string.Format("Товар \"{0}\" был успешно создан", product.Name);
                return RedirectToAction("Index", "Admin");
            }
            TempData["error"] = "Ошибка создания товара, некорректный ввод";
            return RedirectToAction("Create", "Admin");
        }
        [Authorize]
        [HttpPut]
        public async Task<IActionResult> UpdateProduct(Product product)
        {
            return new OkObjectResult(await _productService.UpdateProduct(product));
        }
        [HttpGet]
        public FileContentResult GetImage(Guid productId)
        {
            var product = _productService.GetProductById(productId);
            if (product != null)
                return File(product.Result.ImageData, product.Result.ImageMimeType);
            return null;
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeleteProduct(Guid productId)
        {
            var deleted = await _productService.DeleteProduct(productId);
            TempData["message"] = string.Format("Продукт \"{0}\" был удалён", deleted.Name);
            return RedirectToAction("Index", "Admin");
        }
        [HttpGet]
        public IActionResult ProductInfo(Guid id)
        {
            if (id == null) return RedirectToAction("Index");
            var line = _context.Products.Where(line => line.Id == id).FirstOrDefault();
            return View(line);
        }
        [HttpPost]
        public IActionResult AddReview(Guid id, string text)
        {
            // if (text == null || text=="")
            var line = _context.Products.Where(line => line.Id == id).FirstOrDefault();
            var rev = new Review()
            {
            Text = text
            };
            if (line.Reviews == null)
            {
                //It's null - create it
                line.Reviews = new List<Review>();
            }

            line.Reviews.Add(rev);
            _context.SaveChanges();
            return RedirectToAction("ViewReviews",new { id = line.Id });
        }
        public IActionResult ViewReviews(Guid id)
        {

            //var posts = _context.Products.Where(line => line.Id == id).Select(p => p.Reviews).ToList();
            //var engine = Python.CreateEngine();

            //var path = @"C:\Users\User\OneDrive\DaysBetweenDates.py";
            //var source = engine.CreateScriptSourceFromFile(path);

            //ICollection<string> paths = engine.GetSearchPaths();
            //string dir = @"C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\";
            //paths.Add(dir);
            //string dir2 = @"C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\";
            //paths.Add(dir2);
            //engine.SetSearchPaths(paths);

            //var list = new List<string>();
            //list.Add("");
            //list.Add("null");

            //engine.GetSysModule().SetVariable("argv", list);

            //var eIO = engine.Runtime.IO;
            //var errors = new MemoryStream();
            //eIO.SetErrorOutput(errors, Encoding.Default);

            //var result = new MemoryStream();
            //eIO.SetOutput(result, Encoding.Default);

            //var scope = engine.CreateScope();
            //source.Execute(scope);

            //string st(byte[] x) => Encoding.Default.GetString(x);

            //var output = st(result.ToArray());
            var review = _context.Reviews.Where(item => item.ProductId == id).ToList().Last();
            var python = @"C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe";
            var script = @"C:\Users\User\OneDrive\DaysBetweenDates.py";

            var process = new Process();
            process.StartInfo = new ProcessStartInfo(python, script+" \""+review.Text+"\"")
            {
                //Arguments = " \"null\"",
                UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
        };
            process.Start();

            string output = process.StandardOutput.ReadToEnd();
            review.Sentiment = output;
            _context.SaveChanges();
            process.WaitForExit();
            //string sentiment = "null";

            //psi.Arguments = $"\"{script}\" \"{sentiment}\"";

            


            //var results = "";
            //var errors = "";
            ////using(var process = Process.Start(psi))
            ////{
            //psi.start
            //    results = process.StandardOutput.ReadToEnd();
            //    errors = process.StandardError.ReadToEnd();
            ////}
            //var output = results;
            //var input = errors;

            //Console.WriteLine("Results:");
            //Console.WriteLine(st(result.ToArray()));


            var posts = _context.Reviews.Where(item=>item.ProductId==id).ToList();
            return View(posts);
        }
        //[HttpPost]
        //public IActionResult ProductInfo(string name)
        //{
        //    var line = _context.Products.Include(p => p.Manufacturer).Where(line => line.Name == name).FirstOrDefault();
        //    if (line == null) return RedirectToAction("Index");
        //    return View(line);
        //}
    }
}

Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using SushiBarApp.Abstractions;
using SushiBarApp.Data;
using SushiBarApp.Data.Models;
using SushiBarApp.Hubs;
using SushiBarApp.ViewModels;

namespace SushiBarApp.Controllers
{
    public class Temp
    {
        public static bool isInit = true;
    }
    public class ShopCartController : Controller
    {
        private readonly IProductService _productService;
        SushiAppDBContext _context;
        private readonly ShopCart _shopCart;
        IHubContext<SushiHub> hubContext;


        public ShopCartController(IProductService productService, ShopCart shopCart,
            IHubContext<SushiHub> _hubcontext,SushiAppDBContext context)
        {
            _productService = productService;
            _shopCart = shopCart;
            hubContext = _hubcontext;
            _context = context;
        }
        public PartialViewResult Summary()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;
            return PartialView(_shopCart);
        }
        public IActionResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;
            var obj = new ShopCartViewModel
            {
                ShopCart = _shopCart
            };
            return View(obj);
        }
        [HttpGet]
        public IActionResult GetItemsFromCart()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;
            var obj = new ShopCartViewModel
            {
                ShopCart = _shopCart
            };
            return Ok(obj);
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(Guid id)
        //public IActionResult AddToCart(Guid id)
        {
            if (Temp.isInit)
            {
                _shopCart.ClearShopCart();
                Temp.isInit = false;
            }
            var item = _productService.GetProducts("").Result.FirstOrDefault(i => i.Id == id);
            if(item !=null)
                 await _shopCart.AddToCart(item);
            //_shopCart.AddToCart(item);
            await hubContext.Clients.All.SendAsync("LoadItems");
 
            return RedirectToAction("GetProducts","Product");
        }

        public async Task<IActionResult> RemoveFromCart(Guid productId)
        {
            await _shopCart.RemoveItem(productId);
            await hubContext.Clients.All.SendAsync("LoadItems");
            return RedirectToAction("Index");
        }
        
    }
}

Views/Shared/_Layout.cshtml
@using SushiBarApp.Helpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SushiBarApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="/img/Sushi_icon-icons.com_68684.ico" />
</head>
<body>
    <header>
        <div class="bg-dark collapse" id="navbarHeader" style="">
            <div class="container">
                <div class="row justify-content-center">
                    @*<div class="col-sm-8 col-md-7 py-4">
                            <h4 class="text-white">About</h4>
                        </div>*@
                    <a asp-controller="Product" asp-action="GetProducts" asp-route-categoryName="Суши" class="btn btn-info ml-3">Суши</a>
                    <a asp-controller="Product" asp-action="GetProducts" asp-route-categoryName="Роллы" class="btn btn-info ml-3">Роллы</a>
                    <a asp-controller="Product" asp-action="GetProducts" asp-route-categoryName="Сеты" class="btn btn-info ml-3">Сеты</a>
                    <a asp-controller="Product" asp-action="GetProducts" asp-route-categoryName="Напитки" class="btn btn-info ml-3">Напитки</a>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark box-shadow">
            <div class="container d-flex justify-content-end">
                <a asp-action="GetProducts" asp-controller="Product" class="navbar-brand d-flex align-items-center" style="margin-right: 34%">
                    <strong>Sushi Bar</strong>
                </a>
                <button class="navbar-toggler collapsed mr-2" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.RenderAction("Summary", "ShopCart")
                @Html.RenderAction("AuthState", "Account")
            </div>
        </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>