Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SushiBarApp.Abstractions;
using SushiBarApp.Data.Models;
using Microsoft.AspNetCore.Http;

namespace SushiBarApp.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly Abstractions.IAuthorizationService _authorizationService;
        public AdminController(IProductService productService, ICategoryService categoryService, Abstractions.IAuthorizationService authorizationService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _authorizationService = authorizationService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.Categories = _productService.GetAllCategories();
            if (! await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            return View(await _productService.GetProducts(string.Empty));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid productId)
        {
            ViewBag.Categories = _productService.GetAllCategories();
            if (!await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            return View(await _productService.GetProductById(productId));
        }
        [HttpGet]
        public async Task<IActionResult> EditCategory(Guid categoryId)
        {
            if (!await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            return View( await _categoryService.GetCategory(categoryId));
        }
        [HttpGet]
        public async Task<IActionResult> CreateCategory()
        {
            if (!await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            return View(new Category());
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Product product, IFormFile image = null)
        {
            ViewBag.Categories = _productService.GetAllCategories();
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.Length];
                    image.OpenReadStream().Read(product.ImageData, 0, (int)image.Length);
                }
                await _productService.UpdateProduct(product);
                TempData["message"] = string.Format("Изменения в игре \"{0}\" были сохранены", product.Name);
                return RedirectToAction("Index");
            }
            TempData["error"] = "Ошибка изменения товара, некорректный ввод";
            return View(product);
        }
        [HttpGet]
        public async  Task<IActionResult> Create()
        {
            if (!await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("Login", "Account");
            ViewBag.Categories = _productService.GetAllCategories();
            return View(new Product());
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SushiBarApp.Abstractions;
using SushiBarApp.Data;
using SushiBarApp.Data.Models;
using IAuthorizationService = SushiBarApp.Abstractions.IAuthorizationService;

namespace SushiBarApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IAuthorizationService _authorizationService;
        private readonly ShopCart _shopCart;

        public OrderController(IOrderService orderService,ShopCart shopCart, IAuthorizationService authorizationService)
        {
            _orderService = orderService;
            _shopCart = shopCart;
            _authorizationService = authorizationService;
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            var user = _authorizationService.GetUser(User.Claims);
            if (user == null)
                return View();
            return Checkout(new Order
            {
                Id = Guid.NewGuid(),
                Email = user.Email,
                Name = user.Name,
                OrderTime = DateTime.Now,
                Phone = user.PhoneNumber
            });
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            _shopCart.ListShopItems = _shopCart.GetShopItems();
            if (_shopCart.ListShopItems.Count == 0)
                ModelState.AddModelError("","Ваша корзина пуста");
            if (ModelState.IsValid)
            {
                _orderService.CreateOrder(order);
                return RedirectToAction("Complete");
            }
            return RedirectToAction("Index","ShopCart");
        }
        [HttpGet]
        public IActionResult Complete()
        {
            _shopCart.ClearShopCart();
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
        [HttpGet]
        public IActionResult GetAllOrders()
        {
            var user = _authorizationService.GetUser(User.Claims);
            if (user == null)
                return RedirectToAction("GetProducts", "Product");
            var list = _orderService.GetOrdersByEmail(user.Email);
            return View(list);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetOrdersByAdmin()
        {
            if (! await _authorizationService.IsAdmin(User.Claims))
                return RedirectToAction("GetProducts", "Product");
            var orders = _orderService.GetOrders();
            return View(orders);
        }
        [HttpGet]
        public IActionResult GetOrderDetails(Guid orderId)
        {
            var details = _orderService.GetOrderDetails(orderId);
            return View(details);
        }
    }
}

Views/Order/Checkout.cshtml
@model Order
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Оформление заказа</h1>
<form asp-action="Checkout" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <div class="col-md-5">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Phone"></label>
        <div class="col-md-5">
            <input asp-for="Phone" class="form-control" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <div class="col-md-5">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <input class="btn btn-success" type="submit" value="Завершить заказ"/>
</form>

Views/Order/Complete.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}
<h2>Спасибо!</h2>
<h4>за выбор нашего магазина. Заказ в кратчайшие сроки будет отправлен в службу доставки.</h4>
<a asp-controller="Product" asp-action="GetProducts" class="btn btn-success">Перейти на главную</a>

Views/Order/GetAllOrders.cshtml
@model IEnumerable<Order>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel-heading"><h3>Просмотр заказов</h3></div>
<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th class="text-center">Email</th>
        <th class="text-center">Имя</th>
        <th class="text-center">Телефон</th>
        <th class="text-center">Время заказа</th>
        <th class="text-center">Действия</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-center">@item.Email</td>
            <td class="text-center">@item.Name</td>
            <td class="text-center">@item.Phone</td>
            <td class="text-center">@item.OrderTime</td>
            <td class="text-center">
                <a asp-controller="Order" class="btn btn-link" asp-action="GetOrderDetails" asp-route-orderId=@item.Id>Посмотреть детали</a>
            </td>
        </tr>
    }
</table>
<a class="btn btn-outline-primary" asp-controller="Product" asp-action="GetProducts">Назад</a>

Views/Order/GetOrderDetails.cshtml
@model IEnumerable<OrderDetails>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-heading"><h3>Просмотр деталей заказа</h3></div>
<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th class="text-center">Название товара</th>
        <th class="text-center">Тип товара</th>
        <th class="text-center">Цена товара</th>
        <th class="text-center">Общая цена</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-center">@item.Product.Name</td>
            <td class="text-center">@item.Product.Type</td>
            <td class="text-center">@item.Product.Price</td>
            <td class="text-center">@item.Price</td>
        </tr>
    }
</table>
<a class="btn btn-outline-primary" asp-controller="Order" asp-action="GetAllOrders">Назад</a>

Views/Order/GetOrdersByAdmin.cshtml
@model IEnumerable<Order>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel-heading"><h3>Просмотр заказов всех пользователей</h3></div>
<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th class="text-center">Email</th>
        <th class="text-center">Имя</th>
        <th class="text-center">Телефон</th>
        <th class="text-center">Время заказа</th>
        <th class="text-center">Действия</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-center">@item.Email</td>
            <td class="text-center">@item.Name</td>
            <td class="text-center">@item.Phone</td>
            <td class="text-center">@item.OrderTime</td>
            <td class="text-center">
                <a asp-controller="Order" class="btn btn-link" asp-action="GetOrderDetails" asp-route-orderId=@item.Id>Посмотреть детали</a>
            </td>
        </tr>
    }
</table>
<a class="btn btn-outline-primary" asp-controller="Admin" asp-action="Index">Назад</a>